name: "wepic"
description: "친구와 나를 연결하다 - 위픽"
publish_to: "megabrain"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  home_widget: ^0.4.1
  flutter_cache_manager: ^3.3.1
  get: ^4.6.6
  camera: ^0.10.5+9
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.4
  flutter_native_splash: ^2.3.9
  image_picker: ^1.0.7
  image: ^4.1.4
  device_info_plus: ^9.1.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
